const images = {
  express: require('./expressjs-icon.svg').default,
  react: require('./reactjs-icon.svg').default,
  css: require('./cssIcon.png'),
  github: require('./github-icon-1.svg').default,
  googleMaps: require('./google_maps-tile.svg').default,
  google: require('./google-tile.svg').default,
  javascript: require('./javascript-1.svg').default,
  mongo: require('./mongodb-icon.svg').default,
  node: require('./Node.svg').default,
  sql: require('./sqlite-icon.svg').default,
  html: require('./htmlIcon.svg').default,
  darkMode: require('./darkMode.svg').default,
  lightMode: require('./lightMode.svg').default,
  navLogo: require('./nav-logo.png'),
  fireTracker: require('./fire-tracker.jpg'),
  openAi: require('./open-ai.jpg'),
  noteKeeper: require('./noteKeeper.jpg'),
  readMe: require('./readMe.png'),
  retreatCeremony: require('./retreatCeremony.jpg'),
  hr: require('./hr.png'),
  hrDarkMode: require('./hr-darkmode.png'),
  backgroundDark: require('./DarkModeBackground.jpg'),
  backgroundLight: require('./LightModeBackground.jpg'),
  videoGamesLight: require('./videoGamesLight.svg').default,
  videoGamesDark: require('./videoGamesDark.svg').default,
  weightsLight: require('./weightsLight.svg').default,
  weightsDark: require('./weightsDarkTheme.svg').default,
  hikingLight: require('./hikingLight.svg').default,
  hikingDark: require('./hikingDark.svg').default,
  projectHero: require('./projectPageHero.png'),
  communication: require('./communication.png'),
  teamwork: require('./teamwork.png'),
  adaptability: require('./adapt.png'),
  problemSolving: require('./problemSolving.png'),
  hobbyHero: require('./hobbyHero.png'),

};

export default images;